#warning

#include Notify.inc

| AoW cycle is 3 day +/- 12 hour cycle
| King Tormax is on a 3 day +/- 12 hour cycle

sub main
	/declare mobCount int outer 4
	/call SetupNotifyVars
	|/call setupAnchor
	|/call setupLoot
	
	/call ArrayAdder "King Tormax"
	/call ArrayAdder "The Avatar of War"
	/call ArrayAdder "The Idol of Rallos Zek"
	/call ArrayAdder "The Statue of Rallos Zek"
	
	/echo ---------Notify Kael----------
	
	:notifyLoop
		/call CheckTargets
	/goto :notifyLoop
/return
