#warning

sub main
	/echo ---------AFK Chanter----------
	
	:killLoop
		/assist group
		/if (${Target.Type.NotEqual[Pet]} && ${Target.ID} && ${Target.Distance} < 60 && ${Target.PctHPs} < 80 && !${Target.Dead}) {
			/casting "Polychaotic Assault"
		}
		/if (!(${Me.Aura[Master's Aura].Length} > 0)) /casting Learner's Aura
		/if (${Me.CombatState.NotEqual[COMBAT]} && !${Me.Sitting}) /sit
		/delay 2s
	/goto :killLoop
/return
