
Sub initPriorities
    /declare priorityImmediate  int outer 0
    /declare priorityCombat     int outer 79
    /declare priorityFollowing  int outer 109
    /declare priorityMisc       int outer 129
/return

| 1 My commands / Task / DZ
| 19 Passive Mode
| 29 Cure
| 39 Heal
| 49 Pulling
| -- IN COMBAT --
| 59 Mez
| 69 Tank / grab aggro
| 79 Dps
| -- OUT COMBAT
| 89 Looting
| 99 Anchor
| 109 Following
| 119 Buff
| 129 Misc